<a href="https://colab.research.google.com/github/sinhatter/US-Class-Divergence-vs-World-Convergence/blob/Divergence/US_Class_Divergence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

In [43]:
url = 'https://raw.githubusercontent.com/sinhatter/US-Class-Divergence-vs-World-Convergence/Divergence/Percentage_Income_Quintiles.csv'
df = pd.read_csv(url)

In [44]:
df=df.drop(0)
df=df.drop(1)
df=df.drop(2)
df=df.drop(3)
df=df.drop(4)
df=df.drop(5)
df=df.drop(6)
df.drop('Unnamed: 1', inplace=True, axis=1)

In [45]:
df.columns = ['Year', 'Lowest Fifth', 'Second Fifth', 'Third Fifth', 'Fourth Fifth', 'Highest Fifth', 'Top 5 Percent']

,Year,Lowest Fifth,Second Fifth,Third Fifth,Fourth Fifth,Highest Fifth,Top 5 Percent
7,2020,3.0,8.1,14.0,22.6,52.2,23.0
8,2019,3.1,8.3,14.1,22.7,51.9,23.0
9,2018,3.1,8.3,14.1,22.6,52.0,23.1
10,2017 (40),3.0,8.1,14.0,22.6,52.3,23.2
11,2017,3.1,8.2,14.3,23.0,51.5,22.3
12,2016,3.1,8.3,14.2,22.9,51.5,22.6
13,2015,3.1,8.2,14.3,23.2,51.1,22.1
14,2014,3.1,8.2,14.3,23.2,51.2,21.9
15,2013 (39),3.1,8.2,14.3,23.0,51.4,22.2
16,2013 (38),3.2,8.4,14.4,23.0,51.0,22.2
17,2012,3.2,8.3,14.4,23.0,51.0,22.3
18,2011,3.2,8.4,14.3,23.0,51.1,22.3
19,2010 (37),3.3,8.5,14.6,23.4,50.3,21.3
20,2009 (36),3.4,8.6,14.6,23.2,50.3,21.7
21,2008,3.4,8.6,14.7,23.3,50.0,21.5
22,2007,3.4,8.7,14.8,23.4,49.7,21.2
23,2006,3.4,8.6,14.5,22.9,50.5,22.3
24,2005,3.4,8.6,14.6,23.0,50.4,22.2
25,2004 (35),3.4,8.7,14.7,23.2,50.1,21.8
26,2003,3.4,8.7,14.8,23.4,49.8,21.4
27,2002,3.5,8.8,14.8,23.3,49.7,21.7
28,2001,3.5,8.7,14.6,23.0,50.1,22.4
29,2000 (30),3.6,8.9,14.8,23.0,49.8,22.1
30,1999 (29),3.6,8.9,14.9,23.2,49.4,21.5
31,1998,3.6,9.0,15.0,23.2,49.2,21.4
32,1997,3.6,8.9,15.0,23.2,49.4,21.7
33,1996,3.6,9.0,15.1,23.3,49.0,21.4
34,1995 (25),3.7,9.1,15.2,23.3,48.7,21.0
35,1994 (24),3.6,8.9,15.0,23.4,49.1,21.2
36,1993 (23),3.6,9.0,15.1,23.5,48.9,21.0
37,1992 (22),3.8,9.4,15.8,24.2,46.9,18.6
38,1991,3.8,9.6,15.9,24.2,46.5,18.1
39,1990,3.8,9.6,15.9,24.0,46.6,18.5
40,1989,3.8,9.5,15.8,24.0,46.8,18.9
41,1988,3.8,9.6,16.0,24.2,46.3,18.3
42,1987 (21),3.8,9.6,16.1,24.3,46.2,18.2
43,1986,3.8,9.7,16.2,24.3,46.1,18.0
44,1985 (20),3.9,9.8,16.2,24.4,45.6,17.6
45,1984 (19),4.0,9.9,16.3,24.6,45.2,17.1
46,1983,4.0,9.9,16.4,24.6,45.1,17.0
47,1982,4.0,10.0,16.5,24.5,45.0,17.0
48,1981,4.1,10.1,16.7,24.8,44.3,16.5
49,1980,4.2,10.2,16.8,24.7,44.1,16.5
50,1979 (18),4.1,10.2,16.8,24.6,44.2,16.9
51,1978,4.2,10.2,16.8,24.7,44.1,16.8
52,1977,4.2,10.2,16.9,24.7,44.0,16.8
53,1976 (17),4.3,10.3,17.0,24.7,43.7,16.6
54,1975 (16),4.3,10.4,17.0,24.7,43.6,16.5
55,1974 (16)(15),4.3,10.6,17.0,24.6,43.5,16.5
56,1973,4.2,10.4,17.0,24.5,43.9,16.9
57,1972 (14),4.1,10.4,17.0,24.5,43.9,17.0
58,1971 (13),4.1,10.6,17.3,24.5,43.5,16.7
59,1970,4.1,10.8,17.4,24.5,43.3,16.6
60,1969,4.1,10.9,17.5,24.5,43.0,16.6
61,1968,4.2,11.1,17.6,24.5,42.6,16.3
62,1967 (12),4.0,10.8,17.3,24.2,43.6,17.2

In [46]:
for i in df.iloc[:,0]:
  b=i
  a=b.find("(")
  if(a!=-1):
    b=b[0:a]
  df=df.replace(i,b)
df

,Year,Lowest Fifth,Second Fifth,Third Fifth,Fourth Fifth,Highest Fifth,Top 5 Percent
7,2020,3.0,8.1,14.0,22.6,52.2,23.0
8,2019,3.1,8.3,14.1,22.7,51.9,23.0
9,2018,3.1,8.3,14.1,22.6,52.0,23.1
10,2017,3.0,8.1,14.0,22.6,52.3,23.2
11,2017,3.1,8.2,14.3,23.0,51.5,22.3
12,2016,3.1,8.3,14.2,22.9,51.5,22.6
13,2015,3.1,8.2,14.3,23.2,51.1,22.1
14,2014,3.1,8.2,14.3,23.2,51.2,21.9
15,2013,3.1,8.2,14.3,23.0,51.4,22.2
16,2013,3.2,8.4,14.4,23.0,51.0,22.2
17,2012,3.2,8.3,14.4,23.0,51.0,22.3
18,2011,3.2,8.4,14.3,23.0,51.1,22.3
19,2010,3.3,8.5,14.6,23.4,50.3,21.3
20,2009,3.4,8.6,14.6,23.2,50.3,21.7
21,2008,3.4,8.6,14.7,23.3,50.0,21.5
22,2007,3.4,8.7,14.8,23.4,49.7,21.2
23,2006,3.4,8.6,14.5,22.9,50.5,22.3
24,2005,3.4,8.6,14.6,23.0,50.4,22.2
25,2004,3.4,8.7,14.7,23.2,50.1,21.8
26,2003,3.4,8.7,14.8,23.4,49.8,21.4
27,2002,3.5,8.8,14.8,23.3,49.7,21.7
28,2001,3.5,8.7,14.6,23.0,50.1,22.4
29,2000,3.6,8.9,14.8,23.0,49.8,22.1
30,1999,3.6,8.9,14.9,23.2,49.4,21.5
31,1998,3.6,9.0,15.0,23.2,49.2,21.4
32,1997,3.6,8.9,15.0,23.2,49.4,21.7
33,1996,3.6,9.0,15.1,23.3,49.0,21.4
34,1995,3.7,9.1,15.2,23.3,48.7,21.0
35,1994,3.6,8.9,15.0,23.4,49.1,21.2
36,1993,3.6,9.0,15.1,23.5,48.9,21.0
37,1992,3.8,9.4,15.8,24.2,46.9,18.6
38,1991,3.8,9.6,15.9,24.2,46.5,18.1
39,1990,3.8,9.6,15.9,24.0,46.6,18.5
40,1989,3.8,9.5,15.8,24.0,46.8,18.9
41,1988,3.8,9.6,16.0,24.2,46.3,18.3
42,1987,3.8,9.6,16.1,24.3,46.2,18.2
43,1986,3.8,9.7,16.2,24.3,46.1,18.0
44,1985,3.9,9.8,16.2,24.4,45.6,17.6
45,1984,4.0,9.9,16.3,24.6,45.2,17.1
46,1983,4.0,9.9,16.4,24.6,45.1,17.0
47,1982,4.0,10.0,16.5,24.5,45.0,17.0
48,1981,4.1,10.1,16.7,24.8,44.3,16.5
49,1980,4.2,10.2,16.8,24.7,44.1,16.5
50,1979,4.1,10.2,16.8,24.6,44.2,16.9
51,1978,4.2,10.2,16.8,24.7,44.1,16.8
52,1977,4.2,10.2,16.9,24.7,44.0,16.8
53,1976,4.3,10.3,17.0,24.7,43.7,16.6
54,1975,4.3,10.4,17.0,24.7,43.6,16.5
55,1974,4.3,10.6,17.0,24.6,43.5,16.5
56,1973,4.2,10.4,17.0,24.5,43.9,16.9
57,1972,4.1,10.4,17.0,24.5,43.9,17.0
58,1971,4.1,10.6,17.3,24.5,43.5,16.7
59,1970,4.1,10.8,17.4,24.5,43.3,16.6
60,1969,4.1,10.9,17.5,24.5,43.0,16.6
61,1968,4.2,11.1,17.6,24.5,42.6,16.3
62,1967,4.0,10.8,17.3,24.2,43.6,17.2